[workspace]
members = [
  "bidi",
  "bidi/generate",
  "strip-ansi-escapes",
  "sync-color-schemes",
  "wezterm",
  "wezterm-blob-leases",
  "wezterm-dynamic",
  "wezterm-gui",
  "wezterm-mux-server",
  "wezterm-open-url",
  "wezterm-ssh"
]
resolver = "2"
exclude = [
  "termwiz/codegen"
]

[profile.release]
opt-level = 3
# debug = 2

[profile.dev]
# https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
# Disabled because it breaks builds on Windows
#split-debuginfo = "unpacked"

[patch.crates-io]
xcb = {git="https://github.com/rust-x-bindings/rust-xcb", rev="dbdaa01c178c6fbe68bd51b7ad44c08172181083"} # waiting on a release with https://github.com/rust-x-bindings/rust-xcb/pull/230

